### ISSUE TITLE
Feature For Hex to RGB Color Conversion

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Color.Dev_UI#15]
## Requirements
Create Views and ViewModel that allows conversion of HEX to RGB color

Fork the branch to develop the feature

## Solution
Create an Observable Object ViewModel with Published Properties to feed the converted colours as well as the valid states to the View.

**Comment by DominatorVbN** [comment]
Hey shubham,
I was working on this but I am a bit confused as what will be the output of the hex to RGB conversion

Will it be like

F0FF42 -> rgb(240, 255, 66)
A formated string containing RGB component to something else ?

**Comment by Shubham0812** [comment]
Yeah, that is correct @DominatorVbN  

If the user Inputs say 000000, then the output will be rgb(0, 0, 0)

If you want to go the extra mile, then you can also build a feature where the conversion works even if the user has entered three characters.

Say the user has entered `dca` then, you can duplicate the characters and make it `ddccaa` internally and convert it to rgb(221,204,170)

**Comment by DominatorVbN** [comment]
One more doubt,
As the View for conversion is already created the contribution needed here is just to implement the stubbed function and implement the functionality,

OR should it be a different tab with and new screen and ViewModel ?

**Comment by Shubham0812** [comment]
Yeah buddy, use the existing View itself
